<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subject = [
['id'=>1,'subject_code'=>'003-001','subject_name'=>'ผู้นำจิตอาสาเพื่อการพัฒนาชุมชนอย่างยั่งยืน','subject_credit'=>'3','type_name'=>'สาระที่ 1 ศาสตร์พระราชาและประโยชน์เพื่อนมนุษย์'],
['id'=>2,'subject_code'=>'001-102','subject_name'=>'ศาสตร์พระราชากับการพัฒนาที่ยั่งยืน','subject_credit'=>'2','type_name'=>'สาระที่ 1 ศาสตร์พระราชาและประโยชน์เพื่อนมนุษย์'],
['id'=>3,'subject_code'=>'388-100','subject_name'=>'สุขภาวะเพื่อเพื่อนมนุษย์','subject_credit'=>'1','type_name'=>'สาระที่ 1 ศาสตร์พระราชาและประโยชน์เพื่อนมนุษย์'],
['id'=>4,'subject_code'=>'xxx-xxx','subject_name'=>'ประโยชน์เพื่อนมนุษย์','subject_credit'=>'1','type_name'=>'สาระที่ 1 ศาสตร์พระราชาและประโยชน์เพื่อนมนุษย์'],
['id'=>5,'subject_code'=>'895-001','subject_name'=>'พลเมืองที่ดี','subject_credit'=>'2','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>6,'subject_code'=>'950-101','subject_name'=>'จิตวิวัฒน์','subject_credit'=>'1','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>7,'subject_code'=>'950-102','subject_name'=>'ชีวิตที่ดี','subject_credit'=>'2','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>8,'subject_code'=>'950-102','subject_name'=>'ชีวิตที่ดี','subject_credit'=>'3','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>9,'subject_code'=>'650-192','subject_name'=>'ทักษะชีวิตและความสุข','subject_credit'=>'3','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>10,'subject_code'=>'895-002','subject_name'=>'พัฒนาจิตกับการสื่อสารเพื่อเข้าใจชีวิตมนุษย์','subject_credit'=>'3','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>11,'subject_code'=>'142-239','subject_name'=>'ศิลปะการดำเนินชีวิต','subject_credit'=>'3','type_name'=>'สาระที่ 2 ความเป็นพลเมืองและชีวิตที่สันติ'],
['id'=>12,'subject_code'=>'001-103','subject_name'=>'ไอเดียสู่ความเป็นผู้ประกอบการ','subject_credit'=>'1','type_name'=>'สาระที่ 3 การเป็นผู้ประกอบการ'],
['id'=>13,'subject_code'=>'234-566','subject_name'=>'สรรสร้างความคิด ผลิตนวัตกรรม','subject_credit'=>'1','type_name'=>'สาระที่ 3 การเป็นผู้ประกอบการ'],
['id'=>14,'subject_code'=>'315-201','subject_name'=>'ชีวิตแห่งอนาคต','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>15,'subject_code'=>'820-100','subject_name'=>'รักษ์โลก รักษ์เรา','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>16,'subject_code'=>'820-200','subject_name'=>'เมื่อทะเลปั่นป่วน','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>17,'subject_code'=>'200-103','subject_name'=>'ชีวิตยุคใหม่ด้วยใจสีเขียว','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>18,'subject_code'=>'142-121','subject_name'=>'โลกแห่งอนาคต','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>19,'subject_code'=>'472-115','subject_name'=>'ฉันต้องรอด','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>20,'subject_code'=>'315-104','subject_name'=>'รู้ทันเทคโนโลยีดิจิทัล','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>21,'subject_code'=>'200-107','subject_name'=>'การเชื่อมต่อสรรพสิ่งเพื่อชีวิตยุคดิจิตัล','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>22,'subject_code'=>'142-225','subject_name'=>'ปัจจัยที่ 5','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>23,'subject_code'=>'472-113','subject_name'=>'ดาบสองคม','subject_credit'=>'2','type_name'=>'สาระที่ 4 การอยู่อย่างรู้เท่าทันและการรู้ดิจิทัล'],
['id'=>24,'subject_code'=>'200-108','subject_name'=>'โมบาและการพัฒนากลยุทธ์','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>25,'subject_code'=>'234-565','subject_name'=>'บอร์ดเกมเล่าเรื่อง','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>26,'subject_code'=>'315-202','subject_name'=>'การคิดกับการใช้เหตุผล','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>27,'subject_code'=>'895-011','subject_name'=>'การคิดเพื่อสร้างสุข','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>28,'subject_code'=>'895-012','subject_name'=>'การคิดเชิงบวก','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>29,'subject_code'=>'142-124','subject_name'=>'การแก้ปัญหาแบบสร้างสรรค์','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>30,'subject_code'=>'472-114','subject_name'=>'กบนอกกะลา','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>31,'subject_code'=>'315-100','subject_name'=>'คำนวณศิลป์','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>32,'subject_code'=>'895-010','subject_name'=>'การคิดกับพฤติกรรมพยากรณ์','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>33,'subject_code'=>'142-129','subject_name'=>'คิดไปข้างหน้า','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>34,'subject_code'=>'472-118','subject_name'=>'เงินในกระเป๋า','subject_credit'=>'2','type_name'=>'สาระที่ 5 การคิดเชิงระบบการคิดเชิงตรรกะและตัวเลข'],
['id'=>35,'subject_code'=>'890-001','subject_name'=>'สรรสาระภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>36,'subject_code'=>'890-002','subject_name'=>'ภาษาอังกฤษในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>37,'subject_code'=>'890-003','subject_name'=>'ภาษาอังกฤษพร้อมใช้','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>38,'subject_code'=>'890-004','subject_name'=>'ภาษาอังกฤษยุคดิจิทัล','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>39,'subject_code'=>'890-005','subject_name'=>'ภาษาอังกฤษเชิงวิชาการ','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>40,'subject_code'=>'142-117','subject_name'=>'การเขียนขั้นเทพ','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>41,'subject_code'=>'142-118','subject_name'=>'ภาษาอังกฤษเชิงวิชาการ ฟังและพูด','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>42,'subject_code'=>'142-119','subject_name'=>'ภาษาอังกฤษเชิงวิชาการอ่านและเขียน','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>43,'subject_code'=>'142-215','subject_name'=>'การพูดในที่สาธารณะ','subject_credit'=>'2','type_name'=>'สาระที่ 6 ภาษาและการสื่อสาร'],
['id'=>44,'subject_code'=>'895-020','subject_name'=>'ขิมไทย','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>45,'subject_code'=>'895-021','subject_name'=>'ร้อง เล่น เต้นรำ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>46,'subject_code'=>'895-022','subject_name'=>'จังหวะจะเพลง','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>47,'subject_code'=>'895-023','subject_name'=>'กีตาร์','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>48,'subject_code'=>'895-024','subject_name'=>'อูคูเลเล่','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>49,'subject_code'=>'895-025','subject_name'=>'ฮาร์โมนิกา','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>50,'subject_code'=>'895-026','subject_name'=>'ดูหนังดูละครย้อนดูตน','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>51,'subject_code'=>'895-027','subject_name'=>'อรรถรสภาษาไทย','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>52,'subject_code'=>'895-028','subject_name'=>'การวาดเส้นสร้างสรรค์','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>53,'subject_code'=>'895-030','subject_name'=>'ว่ายน้ำ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>54,'subject_code'=>'895-031','subject_name'=>'เทนนิส','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>55,'subject_code'=>'895-032','subject_name'=>'บาสเกตบอล','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>56,'subject_code'=>'895-033','subject_name'=>'กรีฑา','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>57,'subject_code'=>'895-034','subject_name'=>'ลีลาศ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>58,'subject_code'=>'895-035','subject_name'=>'เปตอง','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>59,'subject_code'=>'895-036','subject_name'=>'ค่ายพักแรม','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>60,'subject_code'=>'895-037','subject_name'=>'แบดมินตัน','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>61,'subject_code'=>'895-038','subject_name'=>'เทเบิลเทนนิส','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>62,'subject_code'=>'895-039','subject_name'=>'การออกกำลังกายเพื่อสุขภาพ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>63,'subject_code'=>'895-130','subject_name'=>'การว่ายน้ำเพื่อช่วยชีวิต','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>64,'subject_code'=>'895-131','subject_name'=>'ฟุตซอล','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>65,'subject_code'=>'315-102','subject_name'=>'สุนทรียศาสตร์การถ่ายภาพ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>66,'subject_code'=>'061-001','subject_name'=>'ความงามของนาฏศิลป์ไทย','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>67,'subject_code'=>'472-116','subject_name'=>'ถักทอเส้นใย เข้าใจท้องถิ่น','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>68,'subject_code'=>'472-117','subject_name'=>'สุขภาพดี ชีวีมีสุข','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>69,'subject_code'=>'142-234','subject_name'=>'โลกสวย','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>70,'subject_code'=>'142-135','subject_name'=>'พับเพียบเรียบร้อย','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>71,'subject_code'=>'142-136','subject_name'=>'ปั้นดินให้เป็นดาว','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>72,'subject_code'=>'142-137','subject_name'=>'ใครๆ ก็วาดได้','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>73,'subject_code'=>'142-138','subject_name'=>'มนต์รักเสียงดนตรี','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>74,'subject_code'=>'142-139','subject_name'=>'ท่องโลกศิลปะ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>75,'subject_code'=>'142-237','subject_name'=>'ดีไซน์เนอร์ชุดดำ','subject_credit'=>'1','type_name'=>'สาระที่ 7 สุนทรียศาสตร์และกีฬา'],
['id'=>76,'subject_code'=>'890-010','subject_name'=>'การพัฒนาทักษะการเขียนภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>77,'subject_code'=>'890-011','subject_name'=>'อ่านได้ใกล้ตัว','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>78,'subject_code'=>'890-012','subject_name'=>'เทคนิคพิชิตการอ่าน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>79,'subject_code'=>'890-013','subject_name'=>'อ่านงานเขียนเชิงวิชาการสำราญใจ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>80,'subject_code'=>'890-014','subject_name'=>'ฝึกสำเนียงผ่านเสียงเพลง','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>81,'subject_code'=>'890-015','subject_name'=>'ไวยากรณ์อังกฤษเพื่อการสื่อสารในชีวิตจริง','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>82,'subject_code'=>'890-020','subject_name'=>'การสนทนาภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>83,'subject_code'=>'890-021','subject_name'=>'ฟังแล้วพูดภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>84,'subject_code'=>'890-022','subject_name'=>'การนำเสนอและการพูดในที่สาธารณะเป็นภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>85,'subject_code'=>'890-023','subject_name'=>'การเรียนรู้ภาษาอังกฤษผ่านทางวัฒนธรรม','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>86,'subject_code'=>'890-024','subject_name'=>'รังสรรค์หนังสั้นภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>87,'subject_code'=>'890-025','subject_name'=>'ทักษะการเรียนภาษาอังกฤษเพื่อการศึกษาต่อ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>88,'subject_code'=>'890-026','subject_name'=>'บูรณาการอ่านเขียนภาษาอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>89,'subject_code'=>'890-027','subject_name'=>'การอ่านและการเขียนภาษาอังกฤษเชิงวิชาการ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>90,'subject_code'=>'890-028','subject_name'=>'ภาษาอังกฤษเพื่อการสื่อสารในที่ทำงาน','subject_credit'=>'1','type_name'=>'รายวิชาเลือก'],
['id'=>91,'subject_code'=>'890-030','subject_name'=>'การสื่อสารภาษาอังกฤษเชิงธุรกิจ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>92,'subject_code'=>'890-031','subject_name'=>'ภาษาอังกฤษในที่ทำงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>93,'subject_code'=>'890-032','subject_name'=>'ภาษาอังกฤษสำหรับนักท่องเที่ยว','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>94,'subject_code'=>'890-033','subject_name'=>'ภาษาอังกฤษสำหรับผู้บริโภคและผู้ประกอบการรุ่นใหม่','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>95,'subject_code'=>'890-040','subject_name'=>'การเขียนเพื่อการสมัครงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>96,'subject_code'=>'890-041','subject_name'=>'ภาษาอังกฤษเพื่อการสัมภาษณ์งาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>97,'subject_code'=>'890-050','subject_name'=>'แปลสิกูเกิล','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>98,'subject_code'=>'890-060','subject_name'=>'ภาษาอังกฤษตลอดเวลา','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>99,'subject_code'=>'890-061','subject_name'=>'ภาษาอังกฤษเพื่อการรู้เท่าทันสื่อดิจิทัล','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>100,'subject_code'=>'890-070','subject_name'=>'พิชิตข้อสอบภาษาอังกฤษเพื่อการทำงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>101,'subject_code'=>'890-071','subject_name'=>'พิชิตข้อสอบภาษาอังกฤษเพื่อการศึกษาต่อ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>102,'subject_code'=>'891-010','subject_name'=>'ภาษาญี่ปุ่นเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>103,'subject_code'=>'891-011','subject_name'=>'สนทนาภาษาญี่ปุ่นในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>104,'subject_code'=>'891-012','subject_name'=>'สนทนาภาษาญี่ปุ่นในที่ทำงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>105,'subject_code'=>'891-020','subject_name'=>'ภาษาจีนเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>106,'subject_code'=>'891-021','subject_name'=>'สนทนาภาษาจีนในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>107,'subject_code'=>'891-022','subject_name'=>'สนทนาภาษาจีนในที่ทำงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>108,'subject_code'=>'891-030','subject_name'=>'ภาษามลายูเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>109,'subject_code'=>'891-031','subject_name'=>'สนทนาภาษามลายูในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>110,'subject_code'=>'891-032','subject_name'=>'สนทนาภาษามลายูเพื่อการท่องเที่ยว','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>111,'subject_code'=>'891-033','subject_name'=>'ภาษามลายูกลางสำหรับสัตวแพทย์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>112,'subject_code'=>'891-034','subject_name'=>'ภาษามลายูถิ่นสำหรับสัตวแพทย์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>113,'subject_code'=>'891-040','subject_name'=>'ภาษาเกาหลีเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>114,'subject_code'=>'891-041','subject_name'=>'สนทนาภาษาเกาหลีในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>115,'subject_code'=>'891-042','subject_name'=>'สนทนาภาษาเกาหลีในที่ทำงาน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>116,'subject_code'=>'891-050','subject_name'=>'ภาษาเยอรมันเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>117,'subject_code'=>'895-040','subject_name'=>'จิตวิทยาความรัก','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>118,'subject_code'=>'895-041','subject_name'=>'ปรัชญาจริยะ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>119,'subject_code'=>'895-042','subject_name'=>'ศิลปะการสื่อสารภาษาไทยในศตวรรษที่ 21','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>120,'subject_code'=>'895-043','subject_name'=>'การใช้ภาษาไทย','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>121,'subject_code'=>'895-044','subject_name'=>'ภาษาไทยร่วมสมัย','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>122,'subject_code'=>'895-045','subject_name'=>'ทักษะการสื่อสาร','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>123,'subject_code'=>'895-046','subject_name'=>'ความคิดและการสื่อสาร','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>124,'subject_code'=>'895-047','subject_name'=>'ประวัติศาสตร์ในภาพยนตร์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>125,'subject_code'=>'895-048','subject_name'=>'การวาดเส้นและระบายสี','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>126,'subject_code'=>'895-049','subject_name'=>'ศิลปะกับความสุข','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>127,'subject_code'=>'895-050','subject_name'=>'ศิลปะในสังคมพหุวัฒนธรรม','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>128,'subject_code'=>'895-051','subject_name'=>'ศิลปวัฒนธรรมร่วมสมัย','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>129,'subject_code'=>'895-054','subject_name'=>'การเรียนรู้ผ่านการท่องเที่ยวแบบประหยัด','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>130,'subject_code'=>'895-055','subject_name'=>'ตะลุยแดนมรดกโลก','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>131,'subject_code'=>'895-056','subject_name'=>'สงขลาศึกษา','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>132,'subject_code'=>'895-057','subject_name'=>'ดนตรีไทย','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>133,'subject_code'=>'895-058','subject_name'=>'สังคีตศิลป์ไทย','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>134,'subject_code'=>'895-059','subject_name'=>'ดนตรีตะวันตก','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>135,'subject_code'=>'895-060','subject_name'=>'การพลศึกษาและนันทนาการ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>136,'subject_code'=>'895-061','subject_name'=>'ฟิตและเฟิร์ม','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>137,'subject_code'=>'895-062','subject_name'=>'ลดเวลานั่ง เพิ่มเวลายืน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>138,'subject_code'=>'895-063','subject_name'=>'อ้วนได้ก็ผอมได้','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>139,'subject_code'=>'895-070','subject_name'=>'ภูมิปัญญาในการดำเนินชีวิต','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>140,'subject_code'=>'895-052','subject_name'=>'การท่องเที่ยวเชิงสร้างสรรค์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>141,'subject_code'=>'895-053','subject_name'=>'การท่องเที่ยวเชิงจิตอาสา','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>142,'subject_code'=>'315-103','subject_name'=>'ความรู้ทั่วไปทางด้านทรัพย์สินทางปัญญา','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>143,'subject_code'=>'348-103','subject_name'=>'การประยุกต์นาโนเทคโนโลยี','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>144,'subject_code'=>'340-103','subject_name'=>'วิทยาศาสตร์ประยุกต์เพื่อชีวิต','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>145,'subject_code'=>'340-151','subject_name'=>'วิทยาศาสตร์และเทคโนโลยีในชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>146,'subject_code'=>'332-100','subject_name'=>'กุญแจไขธรรมชาติ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>147,'subject_code'=>'336-214','subject_name'=>'กินดี ชีวิตดี','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>148,'subject_code'=>'336-215','subject_name'=>'ชีวิตปลอดภัยจากสารพิษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>149,'subject_code'=>'336-216','subject_name'=>'ยาและสุขภาพ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>150,'subject_code'=>'315-204','subject_name'=>'รักษ์ทะเล','subject_credit'=>'2','type_name'=>'รายวิชาเลือก'],
['id'=>151,'subject_code'=>'874-192','subject_name'=>'กฎหมายเพื่อการประกอบอาชีพและการดำเนินชีวิตประจำวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>152,'subject_code'=>'874-193','subject_name'=>'ความรู้เบื้องต้นเกี่ยวกับกฎหมายและกระบวนการยุติธรรม','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>153,'subject_code'=>'874-194','subject_name'=>'ภาษีอากรกับชีวิต','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>154,'subject_code'=>'874-195','subject_name'=>'สิทธิมนุษยชนกับความเป็นพลเมือง','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>155,'subject_code'=>'001-131','subject_name'=>'สุขภาวะกายและจิต','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>156,'subject_code'=>'190-404','subject_name'=>'ธรรมชาติบำบัด','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>157,'subject_code'=>'001-101','subject_name'=>'อาเซียนศึกษา','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>158,'subject_code'=>'142-111','subject_name'=>'ยกเครื่องเรื่องอังกฤษ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>159,'subject_code'=>'142-112','subject_name'=>'อังกฤษออนแอร์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>160,'subject_code'=>'142-115','subject_name'=>'ภาษาอังกฤษสำหรับพื้นฐานเทคโนโลยีสารสนเทศ','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>161,'subject_code'=>'142-116','subject_name'=>'อังกฤษจริตจะก้าน','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>162,'subject_code'=>'142-211','subject_name'=>'อังกฤษกันทุกวัน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>163,'subject_code'=>'142-212','subject_name'=>'ภาษาอังกฤษเพื่อการพัฒนาปัจเจกบุคคล','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>164,'subject_code'=>'142-214','subject_name'=>'ภาษาสื่อและศิลปะการเล่าเรื่อง','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>165,'subject_code'=>'142-224','subject_name'=>'สื่อสร้างสรรค์สำหรับการนำเสนอผลงานวิชาการ','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>166,'subject_code'=>'142-226','subject_name'=>'การออกแบบการนำเสนอแบบสร้างสรรค์สำหรับการประชุมวิชาการและการสื่อสาร','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>167,'subject_code'=>'142-227','subject_name'=>'ทำเงินด้วย Youtube','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>168,'subject_code'=>'142-228','subject_name'=>'การออกแบบผลิตภัณฑ์และการสร้างแบรนด์','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>169,'subject_code'=>'142-229','subject_name'=>'การจัดการสื่อโฆษณาออนไลน์','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>170,'subject_code'=>'142-238','subject_name'=>'ตะลอนทัวร์','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>171,'subject_code'=>'472-106','subject_name'=>'แนวคิดเติบโตสำหรับการนำเสนออย่างมืออาชีพ','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>172,'subject_code'=>'473-001','subject_name'=>'เงินทองต้องรอบรู้','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>173,'subject_code'=>'473-002','subject_name'=>'การอ่านงบการเงินเพื่อการลงทุน','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>174,'subject_code'=>'375-101','subject_name'=>'รู้เท่าทันภาวะฉุกเฉิน','subject_credit'=>'1','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>175,'subject_code'=>'375-102','subject_name'=>'ทักษะการฉุกเฉินเบื้องต้น','subject_credit'=>'2','type_name'=>'รายวิชาเลือก','subject_own_id'=>null],
['id'=>176,'subject_code'=>'347-203','subject_name'=>'สถิติพื้นฐานสําหรับธุรกิจและการประยุกต์ใช้','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>177,'subject_code'=>'460-101','subject_name'=>'หลักการตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>178,'subject_code'=>'460-102','subject_name'=>'การจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>179,'subject_code'=>'460-103','subject_name'=>'หลักการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>180,'subject_code'=>'460-104','subject_name'=>'การจัดการการผลิตและการดําเนินงาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>181,'subject_code'=>'460-201','subject_name'=>'ทักษะการติดต่อสื่อสารทางธุรกิจ','subject_credit'=>'2','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>182,'subject_code'=>'460-301','subject_name'=>'ธุรกิจอัจฉริยะและการวิเคราะห์ข้อมูลเชิงธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>183,'subject_code'=>'460-401','subject_name'=>'การจัดการเชิงกลยุทธ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>184,'subject_code'=>'464-101','subject_name'=>'การบัญชีการเงินเบื้องต้น','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>185,'subject_code'=>'874-293','subject_name'=>'กฎหมายธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>186,'subject_code'=>'876-102','subject_name'=>'หลักเศรษฐศาสตร์พื้นฐานและการประยุกต์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>187,'subject_code'=>'460-202','subject_name'=>'ชุดวิชาดิจิทัล นวัตกรรม และความเป็นผู้ประกอบการ','subject_credit'=>'7','type_name'=>'กลุ่มวิชาแกน','subject_own_id'=>null],
['id'=>188,'subject_code'=>'464-301','subject_name'=>'บัญชีเพื่อการจัดการทางธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>189,'subject_code'=>'473-200','subject_name'=>'การบริหารการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>190,'subject_code'=>'473-201','subject_name'=>'หลักการวางแผนการเงินส่วนบุคคลและภาษี','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>191,'subject_code'=>'473-202','subject_name'=>'สถาบันการเงินและตลาดการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>192,'subject_code'=>'473-301','subject_name'=>'แบบจําลองทางการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>193,'subject_code'=>'473-302','subject_name'=>'การบริหารความเสี่ยงทางการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>194,'subject_code'=>'473-303','subject_name'=>'การวิจัยทางการเงิน 1','subject_credit'=>'2','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>195,'subject_code'=>'473-400','subject_name'=>'การเงินระหว่างประเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>196,'subject_code'=>'473-401','subject_name'=>'การวิจัยทางการเงิน 2','subject_credit'=>'2','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>197,'subject_code'=>'473-304','subject_name'=>'การฝึกงานทางการเงิน','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>198,'subject_code'=>'473-409','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>199,'subject_code'=>'473-410','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>200,'subject_code'=>'473-300','subject_name'=>'ชุดวิชาการลงทุนในหุ้นสามัญเพื่อการสร้างความมั่งคั่ง','subject_credit'=>'5','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>1],
['id'=>201,'subject_code'=>'473-307','subject_name'=>'จรรยาบรรณทางการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>202,'subject_code'=>'473-308','subject_name'=>'การลงทุนในตราสารหนี้','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>203,'subject_code'=>'473-309','subject_name'=>'การคลังสาธารณะ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>204,'subject_code'=>'473-310','subject_name'=>'การบริหารสินเชื่อ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>205,'subject_code'=>'473-402','subject_name'=>'การเงินเพื่อการนําเข้าและส่งออก','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>206,'subject_code'=>'473-403','subject_name'=>'ตราสารอนุพันธ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>207,'subject_code'=>'473-404','subject_name'=>'การวางแผนภาษีและมรดก','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>208,'subject_code'=>'473-405','subject_name'=>'การสร้างแผนการเงินส่วนบุคคลแบบบูรณาการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>209,'subject_code'=>'473-406','subject_name'=>'การเงินเชิงพฤติกรรม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>210,'subject_code'=>'473-411','subject_name'=>'หัวข้อพิเศษทางการเงิน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>211,'subject_code'=>'473-305','subject_name'=>'ชุดวิชาการวางแผนการประกันภัย','subject_credit'=>'5','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>212,'subject_code'=>'473-306','subject_name'=>'ชุดวิชาการวางแผนเพื่อการเกษียณ','subject_credit'=>'9','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>213,'subject_code'=>'473-407','subject_name'=>'ชุดวิชาการวิเคราะห์ข้อมูลเพื่อการบริหารการเงินธุรกิจ','subject_credit'=>'9','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>214,'subject_code'=>'473-408','subject_name'=>'ชุดวิชาการบริหารความเสี่ยงเพื่อการดําเนินธุรกิจที่ยั่งยืน','subject_credit'=>'6','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>1],
['id'=>215,'subject_code'=>'474-101','subject_name'=>'พฤติกรรมผู้บริโภค','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>216,'subject_code'=>'474-201','subject_name'=>'การตลาดแห่งความหลากหลาย','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>217,'subject_code'=>'474-202','subject_name'=>'การจัดการผลิตภัณฑ์และตราสินค้า','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>218,'subject_code'=>'474-203','subject_name'=>'การสื่อสารทางการตลาดเชิงบูรณาการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>219,'subject_code'=>'474-204','subject_name'=>'กลยุทธ์และการวิเคราะห์ราคา','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>220,'subject_code'=>'474-205','subject_name'=>'แผนการตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>221,'subject_code'=>'474-301','subject_name'=>'การตลาดแบบเชื่อมโยงลูกค้าผ่านหลากหลายช่องทาง','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>222,'subject_code'=>'474-302','subject_name'=>'การวิจัยการตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>223,'subject_code'=>'474-303','subject_name'=>'การตลาดดิจิทัล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>224,'subject_code'=>'474-401','subject_name'=>'กลยุทธ์การตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>225,'subject_code'=>'474-304','subject_name'=>'การฝึกงานทางการตลาด','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>226,'subject_code'=>'474-402','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>227,'subject_code'=>'474-403','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>2],
['id'=>228,'subject_code'=>'474-305','subject_name'=>'การตลาดเพื่อสังคม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>229,'subject_code'=>'474-306','subject_name'=>'การตลาดเพื่อชุมชน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>230,'subject_code'=>'474-307','subject_name'=>'การตลาดบริการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>231,'subject_code'=>'474-308','subject_name'=>'การตลาดอาเซียน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>232,'subject_code'=>'474-309','subject_name'=>'การเตรียมฝึกประสบการณ์วิชาชีพการตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>233,'subject_code'=>'474-404','subject_name'=>'การตลาดโลก','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>234,'subject_code'=>'474-405','subject_name'=>'การตลาดสื่อสังคม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>235,'subject_code'=>'474-406','subject_name'=>'การตลาดสําหรับผู้ประกอบการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>236,'subject_code'=>'474-407','subject_name'=>'การบริหารการค้าปลีก','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>237,'subject_code'=>'474-408','subject_name'=>'สัมมนาการตลาด','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>2],
['id'=>238,'subject_code'=>'475-201','subject_name'=>'การวางแผนทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>239,'subject_code'=>'475-202','subject_name'=>'พฤติกรรมองค์การ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>240,'subject_code'=>'475-301','subject_name'=>'การพัฒนาทรัพยากรมนุษย์และองค์การ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>241,'subject_code'=>'475-302','subject_name'=>'กฎหมายเกี่ยวกับการจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>242,'subject_code'=>'475-303','subject_name'=>'การจัดการผลตอบแทน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>243,'subject_code'=>'475-304','subject_name'=>'การจัดการผลการปฏิบัติงาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>244,'subject_code'=>'475-305','subject_name'=>'ภาวะผู้นํา','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>245,'subject_code'=>'475-306','subject_name'=>'การเจรจาต่อรองทางธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>246,'subject_code'=>'475-401','subject_name'=>'การวิจัยทางด้านการจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>247,'subject_code'=>'475-402','subject_name'=>'สัมมนาการจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>248,'subject_code'=>'475-300','subject_name'=>'การฝึกงานทางการจัดการทรัพยากรมนุษย์','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>249,'subject_code'=>'475-400','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>250,'subject_code'=>'475-403','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>3],
['id'=>251,'subject_code'=>'475-311','subject_name'=>'การจัดการสํานักงานยุคใหม่','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>252,'subject_code'=>'475-312','subject_name'=>'การประชาสัมพันธ์องค์การ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>253,'subject_code'=>'475-313','subject_name'=>'การจัดการข้ามวัฒนธรรม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>254,'subject_code'=>'475-321','subject_name'=>'ระบบสารสนเทศเพื่อการจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>255,'subject_code'=>'475-322','subject_name'=>'การออกแบบองค์การ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>256,'subject_code'=>'475-323','subject_name'=>'การจัดการทรัพยากรมนุษย์ระหว่างประเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>257,'subject_code'=>'475-324','subject_name'=>'แรงงานสัมพันธ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>258,'subject_code'=>'475-411','subject_name'=>'หัวข้อพิเศษทางการจัดการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>259,'subject_code'=>'475-421','subject_name'=>'การจัดการทรัพยากรมนุษย์เชิงกลยุทธ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>260,'subject_code'=>'475-422','subject_name'=>'การจัดการบุคลากรที่เป็นเลิศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>261,'subject_code'=>'475-423','subject_name'=>'หัวข้อพิเศษทางการจัดการทรัพยากรมนุษย์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>3],
['id'=>262,'subject_code'=>'476-201','subject_name'=>'ความรู้เบื้องต้นเกี่ยวกับการจัดการโลจิสติกส์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>263,'subject_code'=>'476-202','subject_name'=>'ความรู้เบื้องต้นเกี่ยวกับการขนส่งและการกระจายสินค้า','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>264,'subject_code'=>'476-203','subject_name'=>'การจัดการสินค้าคงคลังและคลังสินค้า','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>265,'subject_code'=>'476-301','subject_name'=>'การจัดซื้อและการจัดหา','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>266,'subject_code'=>'476-302','subject_name'=>'การจัดการและการออกแบบโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>267,'subject_code'=>'476-303','subject_name'=>'การสร้างแบบจําลองโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>268,'subject_code'=>'476-304','subject_name'=>'วิธีวิจัยโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>269,'subject_code'=>'476-305','subject_name'=>'ตัวแบบการหาค่าเหมาะสมที่สุดในการจัดการโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>270,'subject_code'=>'476-401','subject_name'=>'การจัดการการส่งออกและนําเข้า','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>271,'subject_code'=>'476-402','subject_name'=>'สัมมนาการจัดการโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>272,'subject_code'=>'476-300','subject_name'=>'การฝึกงานทางโลจิสติกส์','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>273,'subject_code'=>'476-403','subject_name'=>'โครงงานสําหรับการจัดการโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>274,'subject_code'=>'476-400','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>275,'subject_code'=>'476-410','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>4],
['id'=>276,'subject_code'=>'476-204','subject_name'=>'การจัดการธุรกิจระหว่างประเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>277,'subject_code'=>'476-205','subject_name'=>'การบริหารความสัมพันธ์ลูกค้าสําหรับโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>278,'subject_code'=>'476-306','subject_name'=>'การวางแผนการจัดการทรัพยากรเพื่อการจัดการโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>279,'subject_code'=>'476-307','subject_name'=>'ธุรกิจพาณิชยนาวี','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>280,'subject_code'=>'476-308','subject_name'=>'การบริหารท่าเรือ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>281,'subject_code'=>'476-309','subject_name'=>'การพยากรณ์อุปสงค์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>282,'subject_code'=>'476-310','subject_name'=>'การบริหารจัดการโครงการด้านโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>283,'subject_code'=>'476-404','subject_name'=>'การขนส่งต่อเนื่องหลายรูปแบบ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>284,'subject_code'=>'476-405','subject_name'=>'การจัดการระวางสินค้า','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>285,'subject_code'=>'476-406','subject_name'=>'การบรรจุภัณฑ์สําหรับการจัดการโลจิสติกส์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>286,'subject_code'=>'476-407','subject_name'=>'การบริหารความเสี่ยงในโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>287,'subject_code'=>'476-408','subject_name'=>'การจัดการโลจิสติกส์และโซ่อุปทานเพื่อการช่วยเหลือทางมนุษยธรรม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>288,'subject_code'=>'476-409','subject_name'=>'หัวข้อพิเศษด้านการจัดการโลจิสติกส์และโซ่อุปทาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>4],
['id'=>289,'subject_code'=>'477-101','subject_name'=>'หลักการพื้นฐานระบบสารสนเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>290,'subject_code'=>'477-302','subject_name'=>'เทคโนโลยีแพลตฟอร์มสําหรับคลาวด์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>291,'subject_code'=>'477-102','subject_name'=>'ตรรกะของการใช้โปรแกรมและโครงสร้างข้อมูล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>292,'subject_code'=>'477-201','subject_name'=>'การเขียนโปรแกรมเบื้องต้นทางธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>293,'subject_code'=>'477-301','subject_name'=>'การพัฒนาเว็บขั้นสมบูรณ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>294,'subject_code'=>'477-303','subject_name'=>'การวิเคราะห์และออกแบบระบบสารสนเทศทางธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>295,'subject_code'=>'477-202','subject_name'=>'การจัดการฐานข้อมูล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>296,'subject_code'=>'477-203','subject_name'=>'เครือข่ายคอมพิวเตอร์และความมั่นคงทางไซเบอร์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>297,'subject_code'=>'477-401','subject_name'=>'สัมมนาระบบสารสนเทศทางธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>298,'subject_code'=>'477-304','subject_name'=>'การฝึกงานทางระบบสารสนเทศ','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>299,'subject_code'=>'477-402','subject_name'=>'โครงงานระบบสารสนเทศทางธุรกิจ I','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>300,'subject_code'=>'477-403','subject_name'=>'โครงงานระบบสารสนเทศทางธุรกิจ II','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>301,'subject_code'=>'477-404','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>302,'subject_code'=>'477-405','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>5],
['id'=>303,'subject_code'=>'477-305','subject_name'=>'พาณิชย์อิเล็กทรอนิกส์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>304,'subject_code'=>'477-306','subject_name'=>'ปัญญาประดิษฐ์และการเรียนรู้ของเครื่องจักร','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>305,'subject_code'=>'477-307','subject_name'=>'ทรัพย์สินทางปัญญาสําหรับดิจิทัลคอนเทนท์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>306,'subject_code'=>'477-308','subject_name'=>'การค้นคืนสารสนเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>307,'subject_code'=>'477-309','subject_name'=>'วิทยาการเข้ารหัสลับและเทคโนโลยีบล็อกเชน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>308,'subject_code'=>'477-310','subject_name'=>'การปฏิรูปสู่ดิจิทัล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>309,'subject_code'=>'477-311','subject_name'=>'ระบบฐานข้อมูลขั้นสูง','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>310,'subject_code'=>'477-312','subject_name'=>'การสํารวจและการเตรียมข้อมูล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>311,'subject_code'=>'477-313','subject_name'=>'การเขียนโปรแกรมสําหรับการวิเคราะห์ข้อมูล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>312,'subject_code'=>'477-314','subject_name'=>'การแสดงข้อมูลด้วยแผนภาพ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>313,'subject_code'=>'477-315','subject_name'=>'คลังข้อมูลและเหมืองข้อมูล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>314,'subject_code'=>'477-316','subject_name'=>'การเขียนโปรแกรมทางสถิติ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>315,'subject_code'=>'477-321','subject_name'=>'การออกแบบประสบการณ์สําหรับผู้ใช้งาน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>316,'subject_code'=>'477-322','subject_name'=>'การจัดการโครงการระบบสารสนเทศ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>317,'subject_code'=>'477-323','subject_name'=>'การเขียนโปรแกรมประยุกต์บนอุปกรณ์เคลื่อนที่','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>318,'subject_code'=>'477-324','subject_name'=>'มัลติมีเดีย และการประยุกต์ใช้','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>319,'subject_code'=>'477-331','subject_name'=>'หัวข้อพิเศษทางระบบสารสนเทศทางธุรกิจ 1','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>320,'subject_code'=>'477-332','subject_name'=>'หัวข้อพิเศษทางระบบสารสนเทศทางธุรกิจ 2','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>5],
['id'=>321,'subject_code'=>'478-200','subject_name'=>'ความรู้เบื้องต้นในอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>322,'subject_code'=>'478-201','subject_name'=>'การดําเนินงานด้านไมซ์เสมือนโมเดลธุรกิจ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>323,'subject_code'=>'478-202','subject_name'=>'การจัดการประชุม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>324,'subject_code'=>'478-203','subject_name'=>'การจัดการอาหารและเครื่องดื่ม','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>325,'subject_code'=>'478-301','subject_name'=>'การจัดการสถานที่จัดงานและสิ่งอํานวยความสะดวก','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>326,'subject_code'=>'478-302','subject_name'=>'การจัดการการเดินทางเพื่อเป็นรางวัล','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>327,'subject_code'=>'478-303','subject_name'=>'การจัดการนิทรรศการ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>328,'subject_code'=>'478-304','subject_name'=>'การจัดการอีเวนต์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>329,'subject_code'=>'478-310','subject_name'=>'การวิจัยทางการจัดการไมซ์ 1','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>330,'subject_code'=>'478-401','subject_name'=>'การวิจัยทางการจัดการไมซ์2','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>331,'subject_code'=>'478-305','subject_name'=>'การฝึกงานทางการจัดการไมซ์','subject_credit'=>'0','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>332,'subject_code'=>'478-402','subject_name'=>'เตรียมสหกิจศึกษา','subject_credit'=>'1','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>333,'subject_code'=>'478-403','subject_name'=>'สหกิจศึกษา','subject_credit'=>'8','type_name'=>'กลุ่มวิชาชีพบังคับ','subject_own_id'=>6],
['id'=>334,'subject_code'=>'478-204','subject_name'=>'ความรู้เบื้องต้นในอุตสาหกรรมท่องเที่ยว','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>335,'subject_code'=>'478-205','subject_name'=>'การพัฒนาบุคลิกภาพอย่างมืออาชีพ','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>336,'subject_code'=>'478-306','subject_name'=>'การตลาดสําหรับอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>337,'subject_code'=>'478-307','subject_name'=>'โลจิสติกส์สําหรับอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>338,'subject_code'=>'478-308','subject_name'=>'การจัดการจุดหมายปลายทาง','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>339,'subject_code'=>'478-309','subject_name'=>'การเป็นผู้ประกอบการในธุรกิจไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>340,'subject_code'=>'478-404','subject_name'=>'การออกแบบนวัตกรรมและความคิดสร้างสรรค์สําหรับอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>341,'subject_code'=>'478-405','subject_name'=>'การจัดการอุตสาหกรรมไมซ์อย่างยั่งยืน','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>342,'subject_code'=>'478-406','subject_name'=>'การบริหารความเสี่ยงในอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
['id'=>343,'subject_code'=>'478-407','subject_name'=>'หัวข้อพิเศษทางการจัดการอุตสาหกรรมไมซ์','subject_credit'=>'3','type_name'=>'กลุ่มวิชาชีพเลือก','subject_own_id'=>6],
];
        foreach ($subject as $item) {
            Subject::create($item);
        }
    }
}
